# Generated by Django 3.2.7 on 2021-10-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_id', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('main_text', models.CharField(max_length=300)),
                ('update_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
